---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kedacore
  namespace: keda
spec:
  interval: 5m
  url: https://kedacore.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keda
  namespace: keda
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: keda
      version: 2.15.1
      sourceRef:
        kind: HelmRepository
        name: kedacore
        namespace: keda
      interval: 5m
