---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: goldpinger
  namespace: goldpinger
spec:
  interval: 5m
  url: https://bloomberg.github.io/goldpinger
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: goldpinger
  namespace: goldpinger
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: goldpinger
      version: '*'
      sourceRef:
        kind: HelmRepository
        name: goldpinger
        namespace: goldpinger
      interval: 5m
