---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: eraser
  namespace: eraser-system
spec:
  interval: 5m
  url: https://eraser-dev.github.io/eraser/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: eraser
  namespace: eraser-system
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: eraser
      version: v1.3.1
      sourceRef:
        kind: HelmRepository
        name: eraser
        namespace: eraser-system
      interval: 5m
