---
apiVersion: v1
kind: Namespace
metadata:
  name: my-sample-app

---
apiVersion: v1
kind: LimitRange
metadata:
  name: my-sample-app
  namespace: my-sample-app
spec:
  limits:
  - default: 
      memory: 500M
    defaultRequest: 
      cpu: 100m
      memory: 50M
    max: 
      memory: 400M
    min:
      cpu: 100m
      memory: 5M
    type: Container
