---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: falco
  namespace: falco
spec:
  interval: 5m
  url: https://falcosecurity.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: falco
  namespace: falco
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: falco
      version: '*'
      sourceRef:
        kind: HelmRepository
        name: falco
        namespace: falco
      interval: 5m
